Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

AllCops:
  DisplayCopNames: true
  Exclude:
    - "bin/**/*"
    - "db/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"
    - "tmp/**/*"
    - "git_hooks/**/*"
  TargetRubyVersion: 3.2.2
